name: Debugging Demo
# link: https://docs.github.com/en/actions/how-tos/monitor-workflows/enable-debug-logging
on:
    workflow_dispatch:
    push:

env:
    USER_1: "foo_user"
    USER_2: "bar_user"

jobs:
    debug_job:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout Repo
              uses: actions/checkout@v6
            
            - name: Step 2 - Set USER_1 as USERNAME
              run: |
                echo "USERNAME=$USER_1" >> $GITHUB_ENV
            
            - name: Step 3 - Printing USERNAME
              run: |
                echo "Printing USERNAME env variable from previous step"
                echo "Username ======== $USERNAME"
                exit 1
            
            - name: Step 4 - Printing USER_2
              run: |
                echo $USER_2